/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import {
  AnimationMixer,
} from 'three'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/models/AnimatedTriangle/glTF-Embedded/AnimatedTriangle.gltf')
  console.log('animations')
  console.log(animations);
  const mixer = useState(new AnimationMixer())
  const actions = useRef()
  useEffect(() => {
    actions.current = {

    }
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <scene>
        <mesh material={nodes.mesh_0.material} geometry={nodes.mesh_0.geometry} name="mesh_0" />
      </scene>
    </group>
  )
}
