/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, 'models/avocado/Avocado.gltf')
  const { normal } = props;

  return (
    <group ref={group} {...props} dispose={null}>
      <scene>
        <mesh
          material={normal ? new THREE.MeshNormalMaterial() : materials['2256_Avocado_d']}
          geometry={nodes.Avocado.geometry}
          name="Avocado"
          rotation={[-Math.PI, 0, -Math.PI]}
        />
      </scene>
    </group>
  )
}
