/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { useSpring } from 'react-spring';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/models/flight-helmet/glTF/FlightHelmet.gltf')
  const [ visible, setVisible ] = useState(true);
  const [style, set, stop] = useSpring(() => ({opacity: 1}))

  // Update spring with new props
  set({opacity: 1})

  useEffect(() => {
    const id = setInterval(() => {
      const opacity = Math.random();
      console.log('setting opacity', opacity);
      set({opacity: opacity})
    }, 2000)
    return () => clearInterval(id);
  }, [set]);

  console.log(style.opacity);
  materials.RubberWoodMat.color.set(0xff00ff)
  return (
    <group ref={group} {...props} dispose={null}>
      <scene>
        <mesh opacity={style.opacity.value} onClick={() => console.log("clicked Hose_low")} material={materials.HoseMat} geometry={nodes.Hose_low.geometry} name="Hose_low" />
        <mesh onClick={() => console.log("clicked RubberWood_low")} material={materials.RubberWoodMat} geometry={nodes.RubberWood_low.geometry} name="RubberWood_low" />
        <mesh onClick={() => console.log("clicked GlassPlastic_low")} material={materials.GlassPlasticMat} geometry={nodes.GlassPlastic_low.geometry} name="GlassPlastic_low" />
        <mesh onClick={() => console.log("clicked MetalParts_low")} material={materials.MetalPartsMat} geometry={nodes.MetalParts_low.geometry} name="MetalParts_low" />
        <mesh onClick={() => console.log("clicked LeatherParts_low")} material={materials.LeatherPartsMat} geometry={nodes.LeatherParts_low.geometry} name="LeatherParts_low" />
        <mesh onClick={() => console.log("clicked Lenses_low")} material={materials.LensesMat} geometry={nodes.Lenses_low.geometry} name="Lenses_low" />
      </scene>
    </group>
  )
}
